server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:flowrspot;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS flowrspot
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: validate
        hbm2ddl: validate
jwt:
  secret: PurkmRDAnAaSvmDaAfi
quote:
  api:
    link: http://quotes.rest/qod